"""Source ingestion, chunking, and conversion adapters for VERA."""

from .chunking import (
    Chunk,
    build_chunks_from_blocks,
    chunk_pages,
    detect_heading,
)
from .convert import batch_convert, convert
from .descriptors import (
    PipelineCapabilities,
    PipelineDescriptor,
    PipelineField,
    PipelineFieldChoice,
)
from .formats import (
    installed_source_formats,
    pick_parser_for_suffix,
    pipeline_source_formats,
    resolve_ingest_parser,
    source_mime_type,
    source_suffix,
)
from .markdown import ensure_registered as ensure_markdown_pipeline_registered
from .pipeline import (
    PLUGIN_API_VERSION,
    IngestPipeline,
    UnknownIngestPipelineError,
    clear_ingest_pipeline_cache,
    describe_ingest_pipeline,
    get_ingest_pipeline,
    invoke_ingest_pipeline,
    list_ingest_pipeline_descriptors,
    list_ingest_pipeline_load_errors,
    list_ingest_pipelines,
    prepare_pipeline_options,
    register_ingest_pipeline,
    register_ingest_pipeline_descriptor,
    reset_ingest_pipeline_registry,
)
from .pipeline_options import PipelineOptions
from .types import (
    IngestBlock,
    IngestChunk,
    IngestOptions,
    IngestRequest,
    IngestResult,
    ParsedBlock,
    ParsedPage,
    ensure_ingest_request,
)
from .viewer import (
    chunk_payload,
    export_figures,
    export_source_document,
    figures,
    figures_for,
    get_blocks,
    get_chunk_regions,
    get_page,
    get_source_document,
    regions_for,
    result_payload,
)

__all__ = [
    "Chunk",
    "IngestBlock",
    "IngestChunk",
    "IngestOptions",
    "IngestPipeline",
    "IngestRequest",
    "IngestResult",
    "ParsedBlock",
    "ParsedPage",
    "PLUGIN_API_VERSION",
    "PipelineCapabilities",
    "PipelineDescriptor",
    "PipelineField",
    "PipelineFieldChoice",
    "PipelineOptions",
    "UnknownIngestPipelineError",
    "batch_convert",
    "build_chunks_from_blocks",
    "chunk_pages",
    "chunk_payload",
    "clear_ingest_pipeline_cache",
    "convert",
    "describe_ingest_pipeline",
    "detect_heading",
    "ensure_ingest_request",
    "ensure_markdown_pipeline_registered",
    "export_figures",
    "export_source_document",
    "figures",
    "figures_for",
    "get_blocks",
    "get_chunk_regions",
    "get_ingest_pipeline",
    "get_page",
    "get_source_document",
    "installed_source_formats",
    "invoke_ingest_pipeline",
    "list_ingest_pipeline_descriptors",
    "list_ingest_pipeline_load_errors",
    "list_ingest_pipelines",
    "pick_parser_for_suffix",
    "pipeline_source_formats",
    "prepare_pipeline_options",
    "regions_for",
    "result_payload",
    "register_ingest_pipeline",
    "register_ingest_pipeline_descriptor",
    "reset_ingest_pipeline_registry",
    "resolve_ingest_parser",
    "source_mime_type",
    "source_suffix",
]
