"""Source ingestion, chunking, and conversion adapters for VERA."""

from .chunking import (
    Chunk,
    build_chunks_from_blocks,
    chunk_pages,
    detect_heading,
)
from .convert import batch_convert, convert
from .descriptors import (
    PipelineCapabilities,
    PipelineDescriptor,
    PipelineField,
    PipelineFieldChoice,
)
from .pipeline import (
    IngestPipeline,
    UnknownIngestPipelineError,
    clear_ingest_pipeline_cache,
    describe_ingest_pipeline,
    get_ingest_pipeline,
    invoke_ingest_pipeline,
    list_ingest_pipeline_descriptors,
    list_ingest_pipelines,
    prepare_pipeline_options,
    register_ingest_pipeline,
    register_ingest_pipeline_descriptor,
    reset_ingest_pipeline_registry,
)
from .pipeline_options import PipelineOptions
from .types import (
    IngestBlock,
    IngestChunk,
    IngestOptions,
    IngestRequest,
    IngestResult,
    ParsedBlock,
    ParsedPage,
    coerce_ingest_request,
)
from .viewer import (
    export_source_document,
    figures,
    figures_for,
    get_blocks,
    get_chunk_regions,
    get_page,
    get_source_document,
    regions_for,
)

__all__ = [
    "Chunk",
    "IngestBlock",
    "IngestChunk",
    "IngestOptions",
    "IngestPipeline",
    "IngestRequest",
    "IngestResult",
    "ParsedBlock",
    "ParsedPage",
    "PipelineCapabilities",
    "PipelineDescriptor",
    "PipelineField",
    "PipelineFieldChoice",
    "PipelineOptions",
    "UnknownIngestPipelineError",
    "batch_convert",
    "build_chunks_from_blocks",
    "chunk_pages",
    "clear_ingest_pipeline_cache",
    "coerce_ingest_request",
    "convert",
    "describe_ingest_pipeline",
    "detect_heading",
    "export_source_document",
    "figures",
    "figures_for",
    "get_blocks",
    "get_chunk_regions",
    "get_ingest_pipeline",
    "get_page",
    "get_source_document",
    "invoke_ingest_pipeline",
    "list_ingest_pipeline_descriptors",
    "list_ingest_pipelines",
    "prepare_pipeline_options",
    "regions_for",
    "register_ingest_pipeline",
    "register_ingest_pipeline_descriptor",
    "reset_ingest_pipeline_registry",
]
